- .Rbuildignore
- src/Makevars.win
- tools/winlibs.R
This turned out to be a lot of work, but I created an entirely new `gdal/geos/proj` stack with all of the good stuff for Windows.
To see what's included: https://github.com/rwinlib/gdal2
This uses the usual trick of downloading & static linking on the fly during package build on Windows.
> Add support for Windows using rwinlib builds.

- src/Makevars.win
I think this will fix your windows build. This copies both the `./share` dirs from R winlib into the installation directory so they are bundled with the R binary package.
> Copy share directories into Windows binary package.

- R/geom.R
Edzer,
More a chance to ask you: Why are the roxygen entries not wrapped at 80 characters? CRAN does this anyway, but without it they effectively can't be read from the source (notably not easily at all on github), which is kinda annoying.
> tidy geom.R/st_combine doc entry

- R/read.R
Uses normalizePath in favor of path.expand since the former seems more general (platform independent). Also checks to make sure the dsn is a file before normalizing (handles db connection case).
Added `st_write`'s dsn missing check to both `st_read` and `st_list` for the sake of consistency.
Fixes #68
> Add normalizePath for dsn if it is a file

- R/db.R
Hi, 
`st_read_db` and `st_write_db` are currently losing the projection information when transferring from/to a database.
Most changes needed to fix this are minor. However, in order to make it work for the WKB transfer mode, I had to use EWKB instead of plain WKB (line 115). I am unsure whether this could introduce a portability problem to DBs other than PostGIS. What do you think?
An example:
With the current version of `sf` I get:
```r
data(meuse)
sf <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992)
cr <- st_crs(sf)
cr
#>$epsg
#>[1] 28992
#>
#>$proj4string
#>[1] "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.4171,50.3319,465.5524,-0.398957388243134,0.343987817378283,-1.87740163998045,4.0725 +units=m …
```
> st_read_db and st_write_db now handle and preserve the srid correctly

- R/geom.R
- man/geos.Rd
I think if `length(n) == 1` the *total* sample size should be `n`, not `n * length(x)`.
To implement this is started writing:
```r
if(length(n) == 1)
n = n * l / sum(l)
```
But then was going to add another conditional in case rounding `n` caused problems but then realised it was getting a little complex! Any ideas? It will definitely useful to be able to set n and then distribute them according to line length. 
Happy to say it works now and this is sufficient to solve my problem + like that it gives the user low level access to the number of lines sampled per line.
> Add examples showing how n works in st_line_sample

- R/tidy.R
- tests/testthat/test_tidy.R
`.dots = NULL` is a little trick to save from checking for `missing(.dots)`. I don't know how dangerous it is, but it seems to work fine.
closes #121
> preserve geometry on select

- R/db.R
Hi, 
`st_read_db` does not assign rownames when reading from a database but instead returns them as additional column "row.names" because it is queried using `dbGetQuery`.
Using `dbReadTable` as an alternative would keep rownames but lose the option to specify a `SELECT` query.
Therefore I'd simply suggest to re-assign rownames if a column called "row.names" exists.
A test example:
```r
library(sp)
library(sf)
example(meuse, ask = FALSE, echo = FALSE)
sf <- st_as_sf(meuse)
rownames(sf) <- paste0("rn", 1:nrow(sf))
st_write_db(con , sf, "test")
st_read_db(con, "test")
```
> keep rownames as rownames when reading from db

- R/plot.R
- tests/testthat/test_plot.R
If characters where not converted to factors, `sf.colors()` failed to cut.
> Fail to plot characters

- tests/testthat/test_tm.R
This is a quick fix because the error on CRAN is hard to reproduce.
Fix #127
> test shapefile write within test/ dir

- R/read.R
- tests/testthat/test_read.R
- tests/testthat/test_tm.R
> Allow backslashes in guess_driver

- .Rbuildignore
- codecov.yml
This suppresses the comment message that codecov adds to all pull requests - you can still access the information in the build report pane.
> Suppress codecov comments

- R/crs.R
e.g. so you can use `st_is_latlon()` directly on a crs object.
> Preserve crs objects

- R/graticule.R
I've added a section describing the use of graticules to the documentation, see [discussion](https://github.com/r-spatial/discuss/issues/5)
> add details to graticule

- R/sf.R
- tests/testthat/test_sf.R
The bulk point creation in st_as_sf.data.frame is a bit slow. 
I've short-circuited the creation of the POINT geometries, and also created the sfc structure directly which makes this quite a bit faster. 
For the benchmark below with 1e4 points I see 2 seconds (vs 9 seconds) by vectorizing the `st_point` build and then to < 1 second by further avoiding checks in `st_sfc`
```R
n <- 1e4
set.seed(1)
d <- data.frame(x = rnorm(n), y = rnorm(n), z = rnorm(n), m = rnorm(n), a = seq_len(n))
library(sf)
system.time({
aa <- st_as_sf(d, coords = c("x", "y"), crs = "+init=epsg:4326")
bb <- st_as_sf(d, coords = c("x", "y", "z"))
cc <- st_as_sf(d, coords = c("x", "y", "m"), dim = "XYM")
dd <- st_as_sf(d, coords = c("x", "y", "z", "m"), dim = "XYZM")
})
class(st_geometry(aa)[[1]]) …
```
> speed up bulk point creation from data frame

- R/grid.R
Add grobTree handling for GEOMETRYCOLLECTION.  This PR adds a `st_as_grob.GEOMETRYCOLLECTION` method to collect the component grobs in the gc. 
(I'm using latest sf 059479d   and ggplot2 73e77b6c)
Examples: 
```R
library(sf)
library(ggplot2)
example(st_read)
d1 <- nc[4:7, ]
d1$target <- c("MULTILINESTRING", "MULTIPOINT", "POLYGON", "MULTILINESTRING")
a <- st_sf(geometry = st_sfc(st_geometrycollection(lapply(seq_len(nrow(d1)), 
function(x) st_cast(st_geometry(d1)[[x]], d1$target[x]))), 
st_geometry(nc)[[8]],           st_geometry(nc)[[9]], crs = st_crs(nc)), 
id = 1:3)
ggplot(a, aes(col = id, fill = id, size = id)) + geom_sf()
```
Slightly more realistic use-case with `sfdct`: 
```R
devtools::install_github("mdsumner/sfdct")
library(sfdct)
ct <- ct_triangulate(nc[4:9, ], q = 25, D = TRUE) …
```
> add geometrycollection grob

- R/sfc.R
Example code created a plain data frame but then didnt do anything with it because a line had a #" markdown rather than #', so didn't appear on running ?sfc - edit has a line that creates an sf data frame.
> Make sf data frame in example

- src/geos.cpp
clang output on `-Wall -pedantic` compile of latest version (0.5-1):
```
geos.cpp: In function ‘Rcpp::List CPL_geos_binop(Rcpp::List, Rcpp::List, std::__cxx11::string, double, std::__cxx11::string, bool, bool)’:
geos.cpp:276:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int j = 0; j < tree_sel.size(); j++)
^
geos.cpp:297:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int j = 0; j < tree_sel.size(); j++)
^
geos.cpp:315:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int j = 0; j < tree_sel.size(); j++)
^
```
This fixes that. Note also that travis checks for dependency packages require that they pass `clang/clang++ -Wall -pedantic` (plus other flags), …
> change src/geos.cpp int *.size() -> unsigned *.size()

- DESCRIPTION
The `DBI::dbExecute()` method [appeared in v0.5 of `DBI`](https://cran.rstudio.com/web/packages/DBI/news.html), so `sf` fails to install if using previous `DBI` versions.
> Makes DBI dependency specification stricter (correct)

- R/graticule.R
Fix for graticule not working with ggplot of world2 wrapping around longitude [0,360] https://github.com/r-spatial/sf/issues/421.
```r
library(ggplot2)
library(maps)
devtools::install_github('bbest/sf')
library(sf)
wrld2 = st_as_sf(map('world2', plot=F, fill=T))
ggplot() +
geom_sf(data=wrld2, fill='lightgray') +
coord_sf(xlim=c(140,295), ylim=c(5,60))
```
vs before...
```r
library(ggplot2)
library(maps)
devtools::install_github('r-spatial/sf')
library(sf) 
wrld2 = st_as_sf(map('world2', plot=F, fill=T))
ggplot() +
geom_sf(data=wrld2, fill='lightgray') +
coord_sf(xlim=c(140,295), ylim=c(5,60))
````
> fix for graticule not working with ggplot of world2 wrapping around longitude [0,360]

- R/crs.R
Currently the CRS parsing code in `crs_parameters` doesn't know about projections in kilometers. Here's a quick demo, contrasting with a projection in meters.
```r
library(sf)
km_crs <- "+init=epsg:5070 +units=km"
nc <- st_read(system.file("shape/nc.shp", package="sf")) 
nc_km <- st_transform(nc, "+init=epsg:5070 +units=km")
nc_m <- st_transform(nc, "+init=epsg:5070 +units=m")
sf:::crs_parameters(st_crs(nc_km))  # fails
sf:::crs_parameters(st_crs(nc_m))   # works
sf:::CPL_crs_parameters("+init=epsg:5070 +units=km")[[3]] == "kilometre"  # TRUE
```
> Add km to units sf knows about

- R/crs.R
This is what I get with `sf:::CPL_crs_parameters("+init=epsg:3978 +units=m")[[3]]`
#424
> add SI meter spelling

- R/geom.R
`st_join` always passes the `prepared` parameter, so `st_is_within_distance` should accept it for compatibility.
Also, a minor correction to the error message for `st_equals_exact`.
> Add `prepared` parameter to st_is_within_distance

- R/read.R
On Windows in CJK locale, data sources with multibyte characters cannot be read or write by sf. For example:
```r
library(sf)
dsn_dir <- file.path(tempdir(), "データ")
dir.create(dsn_dir)
nc <- read_sf(system.file("shape/nc.shp", package="sf"))
write_sf(nc, dsn_dir, layer = "nc", driver="ESRI Shapefile")
list.files(dsn_dir)
#> [1] "nc.dbf" "nc.prj" "nc.shp" "nc.shx"
st_layers(dsn_dir)
#> Cannot open data source C:\Users\user1\AppData\Local\Temp\Rtmp21SLMr\データ
#> Error in CPL_get_layers(dsn, options, do_count) : Open failed.
```
`st_read()` and `st_write()` also fails in many cases (I'm not sure why `write_sf()` works in the example above...).
I'm not familiar with GDAL, but it seems that GDAL accepts UTF-8 characters only; it succeeds if we call `CPL_get_layers()` directly with a UTF-8 …
> Fix issues with multibyte string data sources on Windows

- README.md
At the moment the explicit mentions of liblwgeom in the MacOS and Linux sections make it sound a bit like liblwgeom is 'taken care of' by rwinlib when installing from source under Windows.
> Added note to README.md about liblwgeom not being included in Windows install.

- vignettes/sf2.Rmd
The `dropTable` argument in `st_write_db` is now `drop` (see commit 4d187f1, #274). 
You'd still have to update the html file. Too many unrelated changes when I `devtools::build_vignettes()`.
> Update vignette: dropTable is now drop

- R/geom.R
- man/geos_measures.Rd
I apologize for the line ending change on the `st_centroid` example. I cannot figure out how to suppress it.
> add a docs example for st_area

- R/bbox.R
Hi. This should correct a "typo" on crs retrieval for bboxes on `sp` and `Raster` objects, which is using: 
`crs = st_crs(proj4string(meuse)))`
instead than:
`crs = st_crs(proj4string(obj)))`
(the other changes are just automatic removal of end-of-line spaces). 
HTH.
> Correction on crs retrieval on bbox for Raster and sp objects

- R/sf.R
geomtry -> geometry
Apologies, didn't see the note at the top of the manual page. Hope this is now the right place
> fixed typo

- R/plot.R
- man/plot.Rd
Here is the beginning of a color key. It is very basic and doubtless has bugs, but I just want to check you think the approach is OK. The drawing code is copied over from `sp` and simplified a bit.
I don't try to plot a key if there are multiple columns. It could be done, but it would require changing from `par(mfrow)` and/or `layout` to `split.screen` (which claims to nest nicely).
> Add color key

- NEWS.md
> GeoJSON exported as ANSI not UTF-8 on Windows

- src/gdal_write.cpp
- tests/testthat/test_postgis.R
- tests/testthat/test_write.R
It could be split in two P/R if needed... 
Summary:
* use temp files for writing
* cleanup database
* catch warnings
* delete layer on feature failure (#549)
> Cleanup db tests

- DESCRIPTION
- R/tidyverse.R
- tests/testthat/test_tidy.R
Changes:
- Create unnest.sf method, automatically adding the geometry column(s) to the list of list columns that will *not* be unnested.
- Add tests.
- Increase suggested version of tidyr to > 0.7.2 to be able to use `.preserve`. (Note, the CRAN and Github versions are both at 0.7.2, so the tests currently fail.)
- Unindent a few lines in `gather.sf` and `spread.sf` for clearer expression (not part of `if` block).
- Auto-remove a bunch of trailing spaces.
Do you want to hold off merging this until tidyr does a release?
> Add unnest method for sf class

- R/transform.R
description of parameter use_gdal: if package `lwgeom` is not installed, the user gets no clue where to find the function `st_transform_proj`. And since there is no hint what this parameter was supposed to do before it was deprecated, it's not clear for what reason the user should refer to `st_transform_proj`.  
This enhancement tries to provide clues when to use `st_transform_proj` and where to find it.
> little enhancement to documention of st_transform

- R/plot.R
Hi,
this would fix a small glitch in `plot.sf` leading to a crash when trying to plot a single sf point.
This works:
``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.1.2, proj.4 4.9.3
g = st_sfc(st_point(c(1,1)), st_point(c(2,1)), st_point(c(3,1)))
s = st_sf(a=3:5, g)
plot(s)
#> Warning in classInt::classIntervals(na.omit(values), min(nbreaks, n.unq), :
#> n same as number of different finite values\neach different finite value is
#> a separate class
```
This crashes:
``` r
g = st_sfc(st_point(c(1,1)))
s = st_sf(a=3, g)
plot(s)
#> Error in if (asp_box < asp_plt) 1 else 4: missing value where TRUE/FALSE needed
```
plot(s)
> fixes crash on plotting a single sfc point

- NEWS.md
- R/geom.R
- tests/testthat/test_geos.R
I also took the liberty of replacing `dplyr::tbl_df()` with `tibble::as_tibble()`.
Apologies for the extraneous whitespace changes - that's RStudio automatically stripping trailing whitespace - didn't notice until I made the PR. I can revert them if you like.
> Fix #644 - failing binary ops on tbl_dfs with common column names

- R/wkt.R
- man/st_as_text.Rd
Per discussion over in #653.
Note that I removed details line that `EWKT=FALSE` would suppress SRID. `EWKT=FALSE` is the default for `sfc` and `TRUE` for `sfg`. Since `sfg` doesn't carry a CRS, the `EWKT=TRUE` there doesn't cause the SRID to be included.
> Add documentation of WKT and EWKT conventions used in st_as_text.

- tests/testthat/test_write.R
I wonder if there was a reason to not put expectations on the `st_write()`, but there should be expectations. It seems to pass locally...
> test drivers' write mode

- R/sfg.R
I was doing some work with `st_make_grid` and noticed a couple of bottlenecks in the profiler. The changes included in this PR reduce `st_make_grid` runtime by 50% in my testing.
> Optimize st_make_grid

- src/geos.cpp
Necessary if *sf* is loaded but not attached.
> Specify environment where to look for .stop_geos()

- R/read.R
add an extension to the tempfile to get rid of the following GDAL message (cf #628)
```GDAL Message 1: The '' extension is not allowed by the GPKG specification, which may cause compatibility problems```
> add extension to tempfile to calm GDAL

- DESCRIPTION
- configure
- configure.ac
I just had a failure when attempting to install sf on my macbook. Homebrew recently updated gdal to 2.3.0 which apparently requires C++11 within some of its headers. This was causing a failure with the gdal linking checks.
```
checking GDAL: linking with --libs and --dep-libs... no
In file included from gdal_test.cpp:1:
In file included from /usr/local/Cellar/gdal/2.3.0/include/gdal.h:45:
/usr/local/Cellar/gdal/2.3.0/include/cpl_port.h:187:6: error: Must have C++11 or newer.
^
1 error generated.
In file included from gdal_test.cpp:1:
In file included from /usr/local/Cellar/gdal/2.3.0/include/gdal.h:45:
/usr/local/Cellar/gdal/2.3.0/include/cpl_port.h:187:6: error: Must have C++11 or newer.
^
1 error generated.
```
Since a C++ standard isn't specified my compiler was defaulting to C++98 and …
> Change autoconf tests to use C++11

- R/sfc.R
- tests/testthat/test_sfc.R
First proposal #773 
I modified to assign the sum of `st_is_empty()` of sfg object given to `st_sfc (...)`.
Example:
```r
library(sf)
c(st_sfc(st_point(c(NA_real_, NA_real_))),
st_sfc(st_point(c(NA_real_, NA_real_))),
st_sfc(st_point(c(134, 43))))
```
> Enhance `c.sfc()` empty geometry output

- .travis.yml
Works: https://travis-ci.org/pat-s/sf/jobs/397207994
The most recent `tic` version seems to be broken; https://github.com/ropenscilabs/tic/issues/56
cross-ref https://github.com/r-spatial/sf/pull/687#issuecomment-400220114
> Use older tic version to fix deployment of docs

- src/geos.cpp
When GEOS_VERSION_MINOR is 6, the test for PATCH >= 1 fails in 3.7.0rc1 because PATCH is 0rc1. Testing for MINOR first avoids looking at PATCH.
> geos 3.7.0rc1 workaround; GEOS_VERSION_PATCH is 0rc1

- R/bbox.R
For reasons of convenience, I think that `st_bbox.Extent()` should allow the specification of a valid CRS. In its current form, no relevant information is conveyed through the 'crs' attribute of the resulting `bbox` object. 
```r
ext = raster::extent(mapview::breweries)
bbx = sf::st_bbox(ext, crs = 4326) # 'crs' is currently passed to '...', and hence ignored here
str(bbx)
```
However, such information might come in particularly handy when dealing with spatial extents. Using the modified code from pull request:
```r
bbx2 = st_bbox(ext, crs = 4326)
str(bbx2)
```
> Update: enabled CRS for 'Extent' objects.

- R/db.R
``` r
library("RPostgreSQL")
#> Loading required package: DBI
library("sf")
#> Linking to GEOS 3.6.1, GDAL 2.2.3, proj.4 4.9.3
pg_con <-
dbConnect(RPostgreSQL::PostgreSQL(),
host = "localhost",
dbname = "postgis")
nc_sf <-
st_read(system.file("shape/nc.shp", package = "sf"), 
quiet = TRUE)[c("AREA", "NAME", "geometry")]
ft <-
c("AREA"     = "numeric(4,3)",
"NAME"     = "varchar(12)",
"geometry" = "geometry(MultiPolygon,4267)") # crs is EPSG 4267, not 4326
dbWriteTable(
conn = pg_con, 
name = "nc_ft", 
value = nc_sf, 
field.types = ft,
overwrite = TRUE
)
#> [1] TRUE
dbGetQuery(
pg_con, 
"SELECT a.attname as column_name, format_type(a.atttypid, a.atttypmod) AS data_type
FROM pg_attribute a
JOIN pg_class b ON (a.attrelid = b.relfilenode)
WHERE b.relname = 'nc_ft' and a.attstattarget = -1;"
) …
```
> fix #808: field.types don't get dropped anymore

- R/RcppExports.R
- R/geom.R
- man/geos_unary.Rd
- src/RcppExports.cpp
- src/geos.cpp
- tests/testthat/test_geos.R
* `st_buffer` now includes line end and join stylings using optional arguments `endCapStyle`, `joinStyle` and `mitreLimit`, https://github.com/r-spatial/sf/issues/833. 
I believe this is faithful to the support in `rgeos`, which I used as a guide. 
One issue is that these style examples are at the front of 'examples', which seems funny - I'm not sure how to fix apart from moving all the examples into one?
> buffer styles

- .travis.yml
- DESCRIPTION
- tic.R
@krlmlr did a lot of work lately and fixed most of the issues. I cannot fully guarantee that this version is fully stable now but we are close to a CRAN release.
@edzer You can use this branch to solve the test errors. The `tic` implementation looks fine. 
I also tidied the DESCRIPTION using `usethis::use_tidy_description()`
> Use latest version of tic

- src/geos.cpp
This PR fixes two warnings emitted by clang 7. I don't expect this to fix #867.
```
geos.cpp:962:14: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
geom = std::move(geos_ptr(GEOSDifference_r(hGEOSCtxt, geom.get(), out[tree_sel[j]].get()), hGEOSCtxt));
^
geos.cpp:962:14: note: remove std::move call here
geom = std::move(geos_ptr(GEOSDifference_r(hGEOSCtxt, geom.get(), out[tree_sel[j]].get()), hGEOSCtxt));
^~~~~~~~~~                                                                                    ~
geos.cpp:1024:14: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
geom = std::move(geos_ptr(GEOSDifference_r(hGEOSCtxt, geom.get(), inters.get()), hGEOSCtxt)); // cut out inters from geom
^
geos.cpp:1024:14: note: remove std::move …
```
> Remove unnecessary calls to std::move

- DESCRIPTION
- vignettes/sf5.Rmd
Since v2.0, tmap does not convert to `Spatial*` anymore, but uses `sf` internally (see tmap's [NEWS](https://github.com/mtennekes/tmap/blob/3e78bd8e0406f779374d155799247010cebb732d/NEWS#L15), so I deleted the relevant paragraph about the former incompatibility from the sf5 vignette.
I opted for suggesting `tmap (>= 2.0)` in DESCRIPTION. A milder approach would be to state that v2.* is preferred or else there might be limitations (i.e. edit not delete the relevant paragraph in sf5.Rmd). 
I have not yet build the vignette.
> tmap v2.* does not convert to `Spatial*` anymore, uses `sf` internally

- src/geos.cpp
Apparently self-move-assignment of STL objects results in undefined behavior. In this case, `clang` on `OS X` and apparently other platforms drops the reference to a`unique_ptr`'s deleter during self-assignment.
Some discussion/reference: https://stackoverflow.com/q/52960407/2171894
> Fix crash in CPL_nary_intersection (fixes #867)

- src/bbox.cpp
This PR optimizes `CPL_get_bbox` (and in turn, `st_read`) by reducing the number times a vector's length is checked with `Rf_xlength`. According to [discussion elsewhere](https://github.com/RcppCore/Rcpp/issues/629#issuecomment-272170041), this time should be negligible, but I was surprised to see if occupying nearly 20% of total program runtime in a benchmark of a point-in-polygon join that included the calls to `st_read` in the benchmark (see bottom-center of image):
Indeed, storing vector sizes in a variable seems to reduce the `st_read` runtime by a measurable amount:
```
microbenchmark(st_read('basins_lev05.shp'), times=10)
expr      min       lq     mean   median       uq      max neval
st_read("/basins_lev05.shp") 10.46513 10.61681 10.84794 10.81243 11.04343 11.31627    10 …
```
> Optimize bounding-box calculation

- src/bbox.cpp
So this is interesting.
I've been working with a shapefile of ~5500 multipolygons comprising 38000 polygons and 58000 rings. I'm using callgrind to inspect a single `st_read` call:
`R -d "valgrind --tool=callgrind" -e "library(sf); st_read('/tmp/basins_lev05.shp')"
`
The callgrind output shows that, even after the changes recently committed, `CPL_get_bbox` remains at 25% of total program runtime (compared to `CPL_read_ogr` at 43%). `CPL_get_bbox` is still calling `Rf_xlength` an astonishing 69 million times!
Some more digging pins this on the use of `operator()` for vector access instead of `operator[]`. Apparently `NumericVector::operator()` does a bounds-check (and hence, a call to `Rf_xlength`), while `NumericVector::operator[]` does not. So a simple statement like `bb(0) = …
> Further optimize bounding-box calculations

- DESCRIPTION
- R/sfc.R
- tests/testthat/test_wkb.R
Otherwise, with bb53f02934:
``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
geom <- list(st_as_binary(st_point(c(25e5, 12e5))))
st_as_sfc(geom, crs = 2056)
#> Geometry set for 1 feature 
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 2500000 ymin: 1200000 xmax: 2500000 ymax: 1200000
#> epsg (SRID):    NA
#> proj4string:    NA
#> POINT (2500000 1200000)
```
<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> Honor crs argument for st_as_sfc.list()

- configure
- configure.ac
The R version check of configure fails in R-devel because `"${RBIN}" --version | head -1 | cut -f3 -d" "` returns "development" instead of a version string. The following tests expect numbers and fail consequently if confronted with "development".
> harden R version check in configure for use in R devel

- README.md
The instructions are outdated. Homebrew now has an suitable build of gdal in it's mainstream repo.
> readme: update instructions on homebrew

- src/geos.cpp
- tests/testthat/test_geos.R
In playing around with `sf` and some very simple geometries, I noticed that `st_difference` when run on a single `sfc` returned unexpected results in the case where earlier geometries are entirely contained in later geometries. e.g. in the existing test for `st_difference` with fully contained geometries, if we change the order of `pl1` and `pl2` (`pl2` is entirely contained within `pl1`) then
```{r}
library(sf)
pl1 = st_polygon(list(matrix(c(0, 0, 2, 0, 2, 2, 0, 2, 0, 0), byrow = TRUE, ncol=2)))
pl2 = st_polygon(list(matrix(c(0.5, 0.5, 1.5, 0.5, 1.5, 1.5, 0.5, 1.5, 0.5, 0.5), byrow = TRUE, ncol = 2)))
st_contains(pl1, pl2, sparse=FALSE)
out = st_difference(st_sfc(list(pl2, pl1)))
all.equal(out[[2]], pl1)
```
returns `pl1` in it's second geometry, where we'd expect `pl1` with a hole where …
> Fix st_difference on a single sfc so it works on entirely contained geometries correctly.

- R/cast_sfg.R
- tests/testthat/test_st_cast.R
Otherwise:
``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
st_cast(st_multipoint(), "POINT")
#> Warning in st_cast.MULTIPOINT(st_multipoint(), "POINT"): point from first
#> coordinate only
#> Error in is.numeric(x): subscript out of bounds
```
<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
From a quick glance at the code, there are many more such corner cases lurking in the various `st_cast()` implementations. Am I missing a better alternative?
> WIP: Fix corner case for st_cast()

- R/sample.R
I suspect the second one will be faster and yield the same result.
```r
remotes::install_github("r-spatial/sf")
nc = sf::read_sf(system.file("shape/nc.shp", package="sf"))
system.time({p = sf::st_sample(x = nc, size = 1:nrow(nc))})
remotes::install_github("robinlovelace/sf", "update-st_sample_exact")
system.time({p = sf::st_sample(x = nc, size = 1:nrow(nc))})
```
> Fix issue with st_sample exact

- R/sample.R
- man/st_sample.Rd
- man/st_write.Rd
Just a quick PR for the sampling type options in the man. 
It said "only random is implemented right now" despite examples and underlying code for types hexagonal, regular.
> Sample man - type arg

- R/geom.R
This type check avoids a malformed call of `st_simplify(nc, 1e-4)` being interpreted as `st_simplify(nc, dTolerance=0, preserveTopology=TRUE)`.
> Check argument type in st_simplify

- R/db.R
- R/geom.R
- R/read.R
- R/tidyverse.R
- tests/testthat/test_postgis_RPostgres.R
* Silence a quoting warning (03223f3)
* Create tibbles using `new_tibble`
* Test returned class for database
* Add logic to respect `stringsAsFactors` defaults (for tibbles it should be FALSE, for data.frames it should use `default.stringsAsFactors()`, I believe)
As always, happy to make modifications if needed.
> Use new_tibble

- R/tidyverse.R
- tests/testthat/test_tidy.R
`sf::filter.sf()` cannot specify sfc directly.
``` r
library(dplyr, warn.conflicts = FALSE)
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.1, PROJ 6.0.0
d = tibble:::tibble(a = c("A", "B", "C"),
geometry = st_sfc(st_point(c(1, 1)),
st_point(),
st_linestring())) %>% 
st_sf()
d %>% filter(st_is_empty(geometry))
#> Error in UseMethod("st_geometry"): no applicable method for 'st_geometry' applied to an object of class "c('integer', 'numeric')"
```
It can be realized by reference by `.$`
``` r
d %>% filter(st_is_empty(.$geometry))
#> Simple feature collection with 2 features and 1 field (with 2 geometries empty)
#> geometry type:  GEOMETRY
#> dimension:      XY
#> bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
#> epsg (SRID):    NA
#> proj4string:    NA
#> # A tibble: 2 x 2
#>   a …
```
> Allow `filter()` to sfc directly

- R/db.R
- man/st_read.Rd
- tests/testthat/test_postgis_RPostgreSQL.R
This should provide a good solution to the problem of identifying the geometry column from an `RPostgreSQL` connexion. Removing the `type is 0` message is slightly more tricky, but I think this PR provides enough control to the user that they can avoid the problem.
close #1045
> Add `geometry_column` argument for `RPostgreSQL` connexions

- R/graticule.R
This PR quotes the numbers generated in `st_graticule()`, so that these values can be safely passed to `parse()` in any locale (as reported in tidyverse/ggplot2#3365). This doesn't cause any changes in the ggplot2 doppleganger tests (tested using the re-enabled geom_sf() tests in tidyverse/ggplot2#3361), and thus I think it's unlikely that this will cause problems elsewhere (except in ggplot2's own tests, where we'll have to find a different way to test manual breaks in the graticule).
> Quote numbers in graticule labels

- DESCRIPTION
- Users can now directly visit the pkgdown website from the CRAN landing page for sf
- Other pkgdown websites that reference sf functions will now link to the https://r-spatial.github.io/sf/ instead of https://rdrr.io/
> Add pkgdown website to description

- NEWS.md
- R/read.R
- R/wkt.R
- tests/testthat/test_wkt.R
I ran into the issue than long `WKT` couldn't be parsed in `sf`. Apparently line breaks are rejected by OGR.
I wonder if this line should be in `CPL_sfc_from_wkt` or if it's fine to keep it `st_as_sfc.character` since it's the only function calling it?
> Read wkt containing new lines

- configure
- configure.ac
Avoids the following error message during configure:
`checking GEOS version >= 3.4.0... ./configure: line 4170: test: 380dev: integer expression expected`
> Parse GEOS dev version numbers

- R/tidyverse.R
- man/tidyverse.Rd
- tests/testthat/test_tidy.R
**Edited**:
When importing the development version of [tidyr@56fb136a12594c527050357a8b6893509b9fc15b](https://github.com/tidyverse/tidyr/commit/56fb136a12594c527050357a8b6893509b9fc15b), `separate_rows()` fails for sf (it was added in tidyr 0.5.0).
``` r
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.1, PROJ 6.0.0
library(dplyr, warn.conflicts = FALSE)
library(tidyr)
d <- st_as_sf(data.frame(
x = seq_len(3),
y = c("a", "d,e,f", "g,h"),
geometry = st_sfc(st_point(c(1, 1)),
st_point(c(2, 2)),
st_point(c(3, 3))),
stringsAsFactors = FALSE))
d %>% 
separate_rows(y, convert = TRUE)
#> Error: Can't slice a scalar
```
This PR supports `separate_rows()` for sf objects. For a variable with multiple attributes, duplicate lines given the same geometry. 
The previous code is processed as follows.
``` …
```
> Add `separate_rows` method for sf class

- R/sample.R
Three types of spatial sampling: random, hexagonal, and regular. 'regular' was repeated twice - changed to 'random'
> Fix typo in st_sample documentation

- DESCRIPTION
- R/tidyverse.R
- man/tidyverse.Rd
- tests/dplyr.R
- tests/testthat/test_tidy.R
**DO NOT MERGE THIS**
Fixes https://github.com/r-spatial/sf/issues/1068
This PR will
* define `vec_proxy.sfc()` to make `unnest()` and `separate_rows()` work
* remove tests and examples that no longer work
* comment out `nest()` related codes until https://github.com/tidyverse/tidyr/pull/729 is merged
> Fix compatible with tidyr 1.0.0

- DESCRIPTION
I added this in #1145 to test with tidyr 1.0.0. Now that it's released on CRAN, these lines are no more needed (sorry that I didn't do this soon...).
> Remove Remotes field from DESCRIPTION

- R/read.R
Re: https://github.com/r-spatial/sf/issues/1160. Not tested against arbitrary column classes, just `list`
> added warning in clean_columns for dropped columns

- README.md
It isn't necessary for 19.10 eoan, is it?  Please triple-check me, because I'm making some guesses.
It appears to install fine for me without the PPA.  
```sh
E: Failed to fetch http://ppa.launchpad.net/ubuntugis/ubuntugis/ubuntu/dists/eoan/InRelease  403  Forbidden
```
* https://packages.ubuntu.com/eoan/libudunits2-dev
* https://packages.ubuntu.com/eoan/libgdal-dev
* https://packages.ubuntu.com/eoan/libgeos-dev
* https://packages.ubuntu.com/eoan/libproj-dev
> Avoid PPA for newer Ubuntu versions?

- R/wkt.R
- tests/testthat/test_deprecated-db.R
- tests/testthat/test_postgis_RPostgreSQL.R
- tests/testthat/test_postgis_RPostgres.R
- tests/testthat/test_sfg.R
If merged, closes #1219.
As stated in the linked issue, the output of `lwgeom::st_astext()` will continue to omit the inner parens, which will cause an inconsistency unless PostGIS decides to go the same way. 
I know you're working on other higher priority issues (i.e., the `proj` stuff), so no big rush on this.
I have run `revdepcheck::revdep_check()` on all 214 reverse dependencies and found no issues:
``` r
library(revdepcheck)
revdep_report_summary()
#> # Platform
#> 
#> field      value                        
#> ---------  -----------------------------
#> version    R version 3.6.2 (2019-12-12) 
#> os         macOS Mojave 10.14.6         
#> system     x86_64, darwin15.6.0         
#> ui         X11                          
#> language   (EN)                         
#> collate …
```
> Change output of st_as_text() for MULTIPOINT to include inner parens. #1219

- R/grid.R
Fix https://github.com/tidyverse/ggplot2/pull/3681.
Currently, `st_as_grob.sfc_POINT()` assumes the dimension of data is always 2, which results in this incorrect result:
``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
library(ggplot2)
obj_z <- list(st_point(c(1, 1, 1)))
sfc_z <- st_sfc(obj_z)
g <- st_as_grob(sfc_z)
#> Warning in matrix(unlist(x), nrow = 2): data length [3] is not a sub-multiple or
#> multiple of the number of rows [2]
g$x
#> [1] 1native 1native
g$y
#> [1] 1native 1native
```
<sup>Created on 2019-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
This should be handled in the same way as how `plot.sfc_POINT()` does using `length()` of the data.
https://github.com/r-spatial/sf/blob/a71f43f069baf006a859b00db3f15ce0b2ab30b9/R/plot.R# …
> Handle sfc_POINT with Z dimension

- R/read.R
to `new_tibble()`.
This breaks in tibble 3.0.0, and never had an effect to begin with. The `...` expects named arguments, an unnamed list is ignored. On the up side, all arguments in `x` are retained.
> Remove redundant attributes(x) argument

- R/plot.R
- man/plot.Rd
Link to `sf.colors` in `?sf.colors` is redundant
Sorry about the whitespace diff, my editor strips trailing WS
`-w` link for convenience:
https://github.com/r-spatial/sf/pull/1250/files?w=1
> no recursive link in man

- R/geom.R
Giving the arguments `which = "Euclidian"` and `which = "Haussdorff"` (as implied by docs) to `st_distance` throws an error.
Using the corrected spellings gives the anticipated result.
> `Euclidian` and `Haussdorff` distance args misspelled in docs

- src/stars.cpp
I think this should return as per the GDAL documentation - with Y-res = 1. 
Cf https://github.com/r-spatial/sf/pull/1306
This way, the `gdal_read()` function does as GDAL says, and other tools can apply the Y-flip and shift to put a non-geo raster into natural orientation, and with [0, nrow, 0, ncol]. 
I had more to follow up with stars but that's stalled for now
> don't negate Y-res in default geotransform

- R/tidyverse-vctrs.R
with dev vctrs. `vec_restore()` can be called with zero-length input.
> Fix vec_ptype(pt, pt)

- tests/testthat/test_geos.R
- tests/testthat/test_postgis_RPostgres.R
Hi,
Several tests fail in Debian due to some missing R packages that are not officially packaged for Debian. This patch prevents some errors.
https://salsa.debian.org/r-pkg-team/r-cran-sf/-/blob/master/debian/patches/Skip_tests.patch
Best,
Dylan
> Add skip_if_not_installed

- DESCRIPTION
For whatever reason, pkgdown uses the first URL in the DESCRIPTION to do its automagic linking. This tiny edit should fix that for sf!
(what current links to sf look like: https://r-spatial.github.io/stars/articles/stars1.html#cropping-a-rasters-extent ...the dplyr functions automagically link to the dplyr pkgdown site)
> Update URL field to put pkgdown URL first

- src/Makevars.win
- tools/winlibs.R
This is a test run with the [rwinlib/gdal3](https://github.com/rwinlib/gdal3) stack to be able to see if there are unexpected issues in either `sf` or the windows builds. The stack may change, is not ready to be merged.
I think we should wait for R 4.0 before shipping these changes to CRAN because it may cause temporary disruption with the gdal/proj data files and environment variables as some R packages are still using gdal2 and others gdal3.
> Test build GDAL3 stack on Windows

- DESCRIPTION
- NEWS.md
- R/RcppExports.R
- R/read.R
- README.md
- src/RcppExports.cpp
- src/gdal_write.cpp
- tests/testthat/test_read.R
- tests/testthat/test_tidy.R
- tests/testthat/test_write.R
addresses #1345. Reprex:
```r
library(sf)
nc = system.file("gpkg/nc.gpkg", package = "sf")
tf = tempfile(fileext = ".gpkg")
file.copy(nc, tf)
st_layers(system.file("gpkg/nospatial.gpkg", package = "sf"))
a = data.frame(a = c(1L,-3L), b = c("foo", "bar"))
st_write(a, tf, 
layer = "nonspatial_table1",
driver = "GPKG",
delete_layer = TRUE,
layer_options = "ASPATIAL_VARIANT=GPKG_ATTRIBUTES")
st_layers(tf)
(out = read_sf(tf, "nonspatial_table1"))
```
> support writing aspatial tables with st_write()

- R/make_grid.R
- man/st_make_grid.Rd
"lengt 2" changed to "length 2" in description of `offset` argument
> docs(make_grid): Fix minor typo

- R/agr.R
- tests/testthat/test_sf.R
- tests/testthat/test_tidy.R
After subsetting an sf data frame with `[`, the `agr` attribute becomes unnamed:
```r
sf <- st_sf(data.frame(x = st_sfc(st_point(1:2))))
names(attr(sf, "agr"))
#> character(0)
names(attr(sf[, "geometry"], "agr"))
#> NULL
```
The first commit ensure it is named, to make it easier to compare sf data structures in unit tests.
The second commit finishes incomplete unit tests for `sample_n()` and `nest()` (the expectations depend on the agr fix).
> Fix empty `agr` attribute after subset

- .github/workflows/R-CMD-check-with-db.yaml
- .github/workflows/R-CMD-check.yaml
- remove `configure.args` for sf and rgdal
- remove `--no-build-vignettes` build arg
- ensure rgdal installed from source with same libs as sf
- remove ENV vars for sf and xml2
- add cache version env var to enable manual cache invalidation
- Add `GITHUB_PAT` env var to avoid GitHub rate limits (to both actions workflow files)
- use `release` and `oldrel` for R versions rather than specific version numbers
As mentioned in #1401
> Fix macOS GitHub actions

- R/sfc.R
Was trying to find the man page and tried `?sfc_MULTIPOLYGON`, it would be nice to land on `?sfc` from this (to me) natural attempt
> add aliases to ?sfc for sfc_MULTIPOLYGON, etc

- vignettes/sf5.Rmd
`tmap::last_map()` was recently renamed to `tmap::tmap_last()`
> replace deprecated `tmap::last_map()`

- R/RcppExports.R
- R/geom-transformers.R
- man/geos_combine.Rd
- src/RcppExports.cpp
- src/geos.cpp
This provides a large performance boost when unioning polygons that do not overlap.
```
nc <- st_read(system.file("shape/nc.shp", package="sf"))
microbenchmark(
st_union(nc),
st_union(nc, is_coverage=TRUE))
```
A more substantial example is TIGER counties (USA)
```
counties <- st_read('/home/dan/data/tl_2019_us_county.shp')
system.time(a <- st_union(counties))
system.time(b <- st_union(counties, is_coverage=TRUE))
st_area(a)
st_area(b)
```
If the polygons do overlap, an error is thrown:
```
```
> Add is_coverage argument to st_union

- R/plot.R
- man/plot.Rd
allows to have the same colorscale across panels without a visible key
> add key.pos=0 option to run the logic behind the key without plotting it

- DESCRIPTION
- R/geos-overlayng.R
- tests/testthat/test_geos.R
I suggest using the overlay-ng output to complete the test, and re-using that case as a prototype for testing whether we are overlay-ng or not. I haven't exposed the prototype, but did edit DESCRIPTION by  hand (Collate:). `sf:::is_overlayng()` is `TRUE` where I think it should be, and `FALSE` on Windows, which is also correct.
> Detect overlay-ng

- src/gdal.cpp
I noticed that all Authority Codes are assigned to a `crs` object using `$epsg` method, regardless of their name. This could lead to unexpected behaviours, e.g.:
```r
download.file("https://spatialreference.org/ref/sr-org/6974/ogcwkt/", sinu_wkt <- tempfile())
readLines(sinu_wkt, warn = FALSE)
```
```
[1] "PROJCS[\"MODIS Sinusoidal\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Sinusoidal\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",0.0],PARAMETER[\"semi_major\",6371007.181],PARAMETE …
```
> Avoid SR-ORG code to be assigned to $epsg and interpreted as EPSG

- R/tidyverse.R
- Forward `is_coverage` to `st_union`, not `lapply`
- Remove `is_coverage` column from output
> Fix is_coverage argument in summarise.sf

- src/Makevars.win
Fresh binaries with GDAL 3.2.1 and PROJ 7.2.1. Please do test, I think there are some breaking changes!
Update: I don't see any Windows CI here, but all tests have passed on Winbuilder! However I do see a lot of diff output in CMD check, would that be expected?
- R-oldrel: https://win-builder.r-project.org/r0O7Y0A5J63d/
- R-release: https://win-builder.r-project.org/yPv3en0ofLb7/
- R-devel: https://win-builder.r-project.org/U4mm6tcp9GhZ/
> Windows: update to GDAL 3.2.1 stack

- vignettes/sf1.Rmd
- vignettes/sf2.Rmd
- vignettes/sf3.Rmd
- vignettes/sf4.Rmd
- vignettes/sf6.Rmd
- vignettes/sf7.Rmd
This PR fixes some minor typos and format matters found when reading the vignettes.
As always, many thanks for writing detailed documentation on how the functions work!
> Fix minor typos in vignettes

- NEWS.md
- R/grid.R
This PR fixes an issue that surfaced in https://github.com/thomasp85/gganimate/issues/358
My initial implementation forgot to forward grab specific settings pertaining to `pointGrob` when forwarding calls
> Fix st_as_grob issue when plotting mix of MULTI and base type

- R/grid.R
This PR addresses the issue reported in https://github.com/tidyverse/ggplot2/issues/4275
When calling `st_cast_sfc_default()` on a geometry collection the length of the output will (likely) change and the graphical parameters need to be matched up to the new length in order to get rendered as expected
> extent length of graphical parameters after unlisting a geometrycollections

- NEWS.md
- R/RcppExports.R
- R/read.R
- man/st_read.Rd
- src/RcppExports.cpp
- src/gdal_read.cpp
- tests/testthat/test_read.R
Dear `sf` developers, I created this PR to propose the inclusion of a `dialect` argument into `st_read()`. The new argument can be used to choose the _dialect_ used by [`ExecuteSQL`](https://gdal.org/api/gdaldataset_cpp.html#_CPPv4N11GDALDataset10ExecuteSQLEPKcP11OGRGeometryPKc). The idea for including a new parameter into `st_read` started [here](https://gis.stackexchange.com/questions/393540/how-to-extract-unique-values-from-pbf-file-with-gdal). Still, I think that the possibility of selecting the `SQLite` dialect can be useful in other contexts. Hence, I created some examples (taken from [here](https://gdal.org/user/sql_sqlite_dialect.html)) to present the new functionalities: 
``` r
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
nc_path <- system.file("shape/nc.shp", …
```
> Add dialect argument for ExecuteSQL

- NEWS.md
- R/RcppExports.R
- R/read.R
- man/st_read.Rd
- src/RcppExports.cpp
- src/gdal_read.cpp
- tests/testthat/test_read.R
Reverts r-spatial/sf#1646 - see #1653 which needs to be sorted out first - this clearly doesn't work under all circumstances.
> Revert "Add dialect argument for ExecuteSQL"

- R/sfc.R
References #1666. This does not replace the solution in 4911f5a888311384e5e2fb3c781836b0e4f981a0 but greatly improves runtime in other cases where you need to index into an `sfc`. There appear to be other cases that could could benefit from the same technique.
> Remove unclass call from [.sfc

- R/init.R
This avoids a warning in packages that declare methods for this class.
> Add class declaration for sfc_GEOMETRYCOLLECTION

- src/mdim.cpp
Fixes #1687
I'm actually not sure why this doesn't work on 32-bit Windows, I think there is a bug in GDAL. Let's just disable it for now, nobody uses 32-bit windows anymore (but we need to support in R on Windows).
> Disable midm on 32-bit legacy Windows

- README.md
- vignettes/sf3.Rmd
- vignettes/sf4.Rmd
- vignettes/sf5.Rmd
This commit also adds a link in the README to vignette 7 (on spherical
geometry).
> Fixes to spelling, punctuation, capitalization in README & vignettes

- R/sample.R
In the Arugments section, the text for `by_polygons` contained a link to a github issue that had been copied and pasted twice. I just removed the second link.
> Fix typo in sample.R help documentation

- R/terra.R
``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(terra)
#> terra version 1.3.4
x = rast(nrows=108, ncols=21, xmin=0, xmax=1000)
terra::crs(x)
#> [1] ""
```
Before this fix
```r
sf::st_crs(x)
Error in st_crs.character(terra::crs(x)) : invalid crs: 
```
After:
```r
sf::st_crs(x)
#> Coordinate Reference System: NA
```
> improved crs conversion from terra w.r.t. NA

- vignettes/sf7.Rmd
Made a few typo and language fixes, while reading the vignette on S2 last week. A very nice vignette!
Some other notes:
- line 288: something is wrong with the last sentence
- line 310: `uk_sfc = st_as_sfc(uk)`
- the result `uk_sfc` gets 'WGS 84' CRS by default. I presume that this is intended, but I couldn't find it documented somewhere (not for `st_as_sfc()`). Perhaps it is behaviour specific to `s2_geography` objects? Then my suggestion, not for the vignette but for the function docs, would be to document this case.
> vignette sf7 (s2): minor fixes

- DESCRIPTION
- R/geom-transformers.R
- man/geos_unary.Rd
The current implementation of `st_simplify` always returns a warning message when the input object is specified with lat-long coordinates and `sf_use_s2` returns `TRUE` since the argument `preserveTopology` is never evaluated as missing: 
``` r
remotes::install_github("r-spatial/sf", quiet = TRUE)
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1
nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
nc = st_simplify(nc)
#> Warning in st_simplify.sfc(st_geometry(x), preserveTopology, dTolerance):
#> argument preserveTopology is ignored
```
<sup>Created on 2021-09-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
I created this PR to propose a solution that (I think) preserves the original behaviour and removes that warning message when is …
> Change st_simplify

- vignettes/sf7.Rmd
In the vignette introduction, it is said once already, but IMHO rather inconspicuously (boldface added here):
> Most `sf` functions automatically use `s2` functions **when working with ellipsoidal coordinates**; [...]
I suggest to stress this aspect again where the vignette says:
> Starting with `sf` version 1.0, sf uses the new package `s2` (Dunnington, Pebesma, Rubak 2020) for spherical geometry [...]
For some readers it may be not clear enough that `s2` is not going to be used for projected coordinates. It may seem as if `s2` is always going to be used, which isn't the case, so I suggest to make that more visible.
> Vignette sf7 (spherical): stress condition of GEOGCRS for s2

- vignettes/sf7.Rmd
`sf` can use `GEOS` or ~~`sf`~~`s2`.
> Fix a minor typo in sf7.Rmd

- configure
- configure.ac
This adds an `--with-sqlite3-lib` configure argument to specify a non-standard location for sqlite3 libraries. It provides a basic fix for #1471 and #1513.
I'm not sure why runstatedir was removed from configure, so feel free to fix it directly or let me know how I can fix it. I generated configure with autoconf/2.69.
> Add --with-sqlite3-lib configure arg

- DESCRIPTION
- R/sample.R
- man/st_sample.Rd
- tests/spatstat.R
- tests/spatstat.Rout.save
Random generators are being moved from `spatstat.core` to a new package `spatstat.random`.
The proposed changes should hopefully fix the upcoming problem for your package.
> Adapt to new spatstat.random package.

- DESCRIPTION
- R/tidyverse.R
In tidyr 1.2.0 we updated `pivot_longer()`'s `names_transform`, `values_transform`, `names_ptypes` and `values_ptypes` arguments to allow a _single_ function or ptype which will be applied to all columns, rather than requiring a named list. See https://github.com/tidyverse/tidyr/blob/main/NEWS.md#pivoting
This required us to change the default argument from `list()` to `NULL`. In particular, for `names/values_ptypes`, this was important because `list()` should now be interpreted as "use a list ptype for all columns".
For backwards compatibility with sf and a few other packages that extend `pivot_longer()`, we have temporarily forced `list()` to be interpreted as `NULL`, but we would like to remove this behavior. See https://github.com/tidyverse/tidyr/issues/1296.
This PR is a step towards …
> Update `pivot_longer()` signature

- src/Makevars.win
Wrap-up GDAL update for R 3.3.0 - 4.1.3 on Windows. Also adds support for zstd tiff files. This update does not affect the new R-4.2 ucrt builds which you have hardcoded separately in [src/Makevars.ucrt](src/Makevars.ucrt).
> Windows: update GDAL 3.4.1 for R < 4.2

- sf.Rproj
If we edit project code in RStudio, the option to strip trailing whitespace is enabled by default. Currently, this generates large code differences. Disabling this option will make it easier to track changes in the code.
> Don't strip whitespaces in RStudio project

- R/tidyverse.R
- man/tidyverse.Rd
Adding drop_na to the tidyverse functions for sf objects
> Tidyr drop na

- src/Makevars.ucrt
- src/Makevars.win
When attempting to build sf from source on my work (Windows) computer I get the following error.
```
cp -r C:/Program Files/rtools42/x86_64-w64-mingw32.static.posix/share/gdal ../inst/
cp: cannot stat 'C:/Program': No such file or directory
cp: cannot stat 'Files/rtools42/x86_64-w64-mingw32.static.posix/share/gdal': No such file or directory
make: *** [Makevars.ucrt:12: winlibs] Error 1
ERROR: compilation failed for package 'sf'
```
This appears to be because my rtools42 directory is inside "Program Files" which has a space in the name.
I do not have control over where Rtools is installed.
Adding quotes around the `cp` command paths in Makevars.ucrt resolves the error for me.
I also made an analogous change to Makevars.win.
@kadyb suggested I propose these changes here after making …
> Update Makevars for Windows

- R/aggregate.R
I believe this pull request resolves the underlying issue behind #2005  better than (now closed) #2006 
If we ask S2 to return only polygon intersections - which is possible, I just did not realise it when composing the previous pull - it will not be necessary to do any filtering.
In case of planar intersection the `dimensions = "polygon"` part of the intersection call would be safely ignored.
> another shot at #2005 - asking s2 to ignore line & point intersections

- NEWS.md
- R/sfc.R
This will improve https://github.com/r-spatial/sf/issues/2008#issuecomment-1309530848 and https://github.com/r-spatial/sf/issues/1879#issuecomment-1009185571. I ran the local and GHA tests and nothing seems to break. With this PR, I see a reduced output size of ~9 times in `st_distance(by_element = TRUE, which = "Euclidean")` and ~5 times in `st_coordinates()`.
```r
n = 10000
df1 = st_as_sf(data.frame(x = runif(n), y = runif(n)), coords = 1:2, crs = 3857)
df2 = st_as_sf(data.frame(x = runif(n), y = runif(n)), coords = 1:2, crs = 3857)
dist = st_distance(df1, df2, by_element = TRUE, which = "Euclidean")
format(object.size(x), units = "auto")
format(object.size(st_coordinates(df1)), units = "auto")
```
| **Function**      | **Before [Kb]** | **After [kB]** | …
> drop the rownames in `st_coordinates()`

- R/tidyverse.R
- tests/testthat/test_tidy.R
`group_split.sf()` for rowwise_df warns that `.keep` is ignored as follows, 
so I modified the behavior of `group_split.sf()` for rowwise_df.
``` r
suppressMessages(require(sf, quietly = TRUE))
suppressMessages(require(dplyr, quietly = TRUE))
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
out <- nc %>%
rowwise() %>%
group_split()
#> Warning: .keep is ignored in group_split(<rowwise_df>)
```
<sup>Created on 2022-11-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Ignores the `.keep` of `group_split.sf()` for rowwise_df

- R/sp.R
- tests/testthat/test_sp.R
https://github.com/r-spatial/evolution/issues/9, https://github.com/rstudio/leaflet/issues/833
This is not optimized at all, but since it is unlikely to be entered unless someone has canned, stale **sp** polygon objects in their workflows, speed doesn't matter. Here the workhorse is: `st_contains_properly(raw0[!holes], raw0[holes])`, where `holes` are got from the input object. If no holes were assigned initially, the flow of control reverts effectively to the previous code. `st_contains_properly()` may fail if a quasi-hole shares a border segment with its containing exterior ring. Holes are assigned as interior rings to  exterior rings in order of exterior ring area from smallest to largest (the nested island/holes case), and assigned holes the dropped from the larger exterior rings.
> for #2063; reproducing rgeos workflow for assigning interior to exterior rings

- R/sfc.R
This PR is a follow up to https://github.com/r-spatial/sf/issues/1616. 
It adds a few sentences to `st_coordinates()` man page to clarify how one can identify exterior rings and interior holes. 
Note that I couldn't build the corresponding `.Rd` file because I don't have gdal configured locally
> add to details in st_coordinates() 

- R/sp.R
This should work with older GEOS; not checked for `lwgeom` for #2069 . Looks like  
> CAPI: GEOSMakeValidWithParams new validity enforcement approach from https://github.com/locationtech/jts/pull/704, uses GeometryFixer (Paul Ramsey, Martin Davis)
https://github.com/libgeos/geos/blob/3.11.1/NEWS.md in 3.10.0.
> Coerce comments

- R/geom-measures.R
Update docs for `st_distance()` to reflect behaviour of `by_element` parameter since v1.0.9 (#2062)
> Update docs for st_distance

- README.md
Fixes #1982.
The Intel and Apple Silicon versions of Homebrew use different directory prefixes (/usr/local and /opt/homebrew, respectively). This change uses the brew command to determine the prefix.
> Update Homebrew instructions for Mac on Apple Silicon

- tests/testthat/test_tidy.R
for `separate()`, `separate_rows()`, and `nest()`
> skip if require('tidyr') failed

- .github/workflows/pkgdown.yml
- .github/workflows/rcmdcheck.yml
- README.md
If everything works, then I think we can remove `tic.yml`, `update-tic.yml` (and related badges in README), and `tic.R`.
> add new CI workflows (fixes #2129)

- R/plot.R
Here is an attempt to describe plotting order and how to modify it. I did not include any examples, as I dont know any overlapping polygons without importing from other packages, such as rtop. Do you find it useful?
> Describing plotting order for polygons

- NEWS.md
- R/sample.R
- configure
- configure.ac
- man/st_sample.Rd
- src/geos.cpp
- src/stars.cpp
See e.g. https://lin-ear-th-inking.blogspot.com/2020/05/jts-overlay-next-generation.html
I think this can only be considered progress, so suggest to merge with main.
> Integrate GeosNG into sf

- R/tidyverse.R
- vignettes/sf1.Rmd
In this PR:
- Minor improvement to description of MULTIPOLYGON structure in vignette sf1: The text gives the impression that the example is about multiple polygons, by which the existence of only one polygon in the example is not intuitive. This minor edit aims to make it clear.
- Fix minor wording typo in vignette sf1.
> minor improvement to description of MULTIPOLYGON structure in vignette sf1

- R/break_antimeridian.R
- R/db.R
- R/sample.R
- R/sf.R
- R/shift_longitude.R
As identified by `lintr::vector_logic_linter()`.
`&&` and `||` are appropriate inside `if()` / `while()` conditions, where passing a vector is incorrect (maybe an error, depending on the R version, and if not, has possibly misleading behavior).
`&&`/`||` also have early exit where `&`/`|` do not, c.f. `TRUE || stop('hi')` vs. `TRUE | stop('hi')`.
> Use scalar logical operators where appropriate

- R/read.R
- man/st_read.Rd
Follow-up to 3362108a005ab77ba83953430dbaa6edf4b26075 for #2179
I think this more completely fills out the documentation. It makes sense to mostly punt upstream to GDAL here, so sf doesn't need to keep updating this man page as the VSI interface evolves. zip/gz/curl pieces should be pretty stable, so safe to mention here.
> further clarify st_read() of .zip files

- src/geos.cpp
I was getting a compiler warning when running `roxgenize()` for #2181.
The variable is only used if the right `GEOS_VERSION_MINOR` is set, e.g.
https://github.com/r-spatial/sf/blob/3362108a005ab77ba83953430dbaa6edf4b26075/src/geos.cpp#L969-L973
A similar approach is taken elsewhere:
https://github.com/r-spatial/sf/blob/3362108a005ab77ba83953430dbaa6edf4b26075/src/geos.cpp#L199-L203
> hide unused variable when unused

- R/plot.R
`lintr::object_usage_linter()` points out that `nbreaks.missing` is unused; my guess it was intended to be used as here:
https://github.com/r-spatial/sf/blob/3362108a005ab77ba83953430dbaa6edf4b26075/R/plot.R#L80
> Use stored value of missing(nbreaks)

- R/bbox.R
- R/geom-predicates.R
- R/graticule.R
- R/m_range.R
- R/sfg.R
- R/transform.R
- R/wkb.R
- R/z_range.R
- demo/bm_wkb.R
Identified by `lintr::conjunct_test_linter()`.
Compare:
```r
x = TRUE
y = FALSE
stopifnot(x, y)
```
The latter gives a much friendlier failure message.
Alternatively, we could use the R>=4 feature (happy to make the change):
```r
stopifnot("Both x and y must be TRUE" = x && y)
```
Note that the code works on R<4, just that it gives the earlier, less-friendly failure message.
> Avoid && in stopifnot() conditions

- R/break_antimeridian.R
- R/sample.R
- R/sp.R
Identified by `lintr::seq_linter()`.
I didn't see enough input validation to ensure that a length-0 input doesn't wind up running `1:0` accidentally in these cases, hence `seq_along()`/`seq_len()` should be preferred.
> Avoid 1: for possibly-empty input

- R/agr.R
- R/db.R
- R/geom-transformers.R
- R/grid.R
- R/plot.R
- R/sf.R
- R/sfc.R
- R/stars.R
Identified by `lintr::any_is_na_linter()`.
`any(is.na(x))` is equivalent to `anyNA()` in all but the most contrived examples, except that it runs faster and is usually easier to read.
> Use anyNA() where possible

- R/read.R
Identified by `lintr::any_duplicated_linter()`.
Technically the output of `anyDuplicated()` is an integer, not logical, so some authors might prefer `anyDuplicated(fld_names) > 0L` (as e.g. suggested by the tidyverse style guide: https://style.tidyverse.org/syntax.html#implicit-type-coercion). Let me know & I can update.
> use anyDuplicated() over unique() equivalent

- R/proj.R
- R/wkb.R
This should be faster and more readable.
There is one more usage:
https://github.com/r-spatial/sf/blob/ff5104869a78d15efa41acbb073ae2bcdd6135d6/R/crs.R#L338
But `grepl()` has some difference with respect to `NA_character_` input, so the technical equivalent would be `!is.na(x[["input"]]) && startsWith(x[["input"]], "EPSG:")`, not quite as clean (though it may be preferable to expose the NA checking explicitly.
> Use startsWith() over substr()

- R/plot.R
When plotting multiple character/factor-valued columns of an `sf` object, an error occurs when requesting a key because a portion of the code intended for numeric `values` gets executed (`classInt::classIntervals()`). I added lines to convert character `values` to a factor, and to check for numeric `values` before using `classIntervals()`. The changes solve the issue for me.
> Fix issue with key in plot.R

- R/sf.R
Apologies for opening this as a PR, rather than as an issue, but I wanted to confirm this would actually work before I brought it up.
Right now, as mentioned in https://github.com/r-lib/pillar/issues/552 , print methods for sf objects inheriting from tibbles is a bit broken if sf is not loaded in the session. This primarily impacts serialized objects, which might be read in via (for example) `readRDS()` without loading sf. The obvious fix for this is to load sf before loading the object, but it can be hard to identify this from the traceback that's returned.
ggplot2 and, as of today, patchwork handle this by attaching a reference to their package namespace to their objects, so that the serialized object winds up loading the package and therefore the correct print methods -- for instance …
> Quietly load sf namespace when loading sf objects, for improved printing?

- R/tidyverse.R
- tests/testthat/test_tidy.R
Fix #2215 that `"sf_column"` attribute are not changed when renaming a geometry column with `rename_with()`.
> Fix `rename_with()` to correctly change sf_column attribute (#2215)

- R/sf.R
- man/sf.Rd
As I looked at the documentation but overlooked this option for `i` I thought it might be useful to improve the documentation
> Clarify documentation #2199

- R/tidyverse.R
- man/tidyverse.Rd
- tests/testthat/test_tidy.R
Fix #2220.
`NextMethod()` called within `rename_with()` and `pivot_wider()` could not properly handle unquoted arguments for tidy-select.
Therefore, it was modified to call those functions after changing them to data frames.
Also, the order of `pivot_wider()` arguments has been changed to match the order in tidyr 1.3.0.
> Fix `rename_with()` and `pivot_wider()` to work for unquoted arguments

- DESCRIPTION
- R/read.R
- src/gdal_read_stream.cpp
This PR seeks to eliminate differences between `use_stream = TRUE` and `use_stream = FALSE`. It (1) uses wk's WKB -> sfc conversion when using `use_stream = TRUE` because it (now) supports `promote_multi = TRUE`, and (2) prefers "geometry" as the geometry column name.
@edzer I know you commented this out on the last PR, but it seems that when using the usual `read_sf()` we always get "geometry" as the geometry column name for shapefiles and flatgeobuf (but not for gpkg?). I think I am just missing where exactly this value gets set, but the hack I have here just converts "wkb_geometry" to "geometry".
Before this PR:
``` r
library(sf)
#> Linking to GEOS 3.12.0, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
nc_file <- system.file("shape/nc.shp", package = "sf")
waldo::compare(
read_sf(nc_file, …
```
> Improve reading with `use_stream = TRUE`

- R/plot.R
This is minor, but I have `options(warnPartialMatchArgs = TRUE)` set locally. This generates warnings when I plot with sf, as there are a couple of places where argument names are not fully spelled out. This PR fixes that in the places that I could find.
> Eliminate partial matching of args in plot methods

- R/valid.R
- man/dbWriteTable.Rd
- man/valid.Rd
The sfg class was listed twice, while sfc was not listed.
Meanwhile `dbWriteTable.Rd` has been brought in-sync.
> st_is_valid(), st_make_valid(): fix docs of x argument

- configure
- configure.ac
Small fix for when we are cross compiling, for example linux to macos or linux to webassembly.
In those cases we can't run test programs (because they are for another architecture).
Autoconf automatically sets the `cross_compiling` variable based on `--host` or `--build` arguments being passed (see the output configure for details).
> Fix cross-compiling

- R/geom-measures.R
This PR adds a new function `st_perimeter()`. It was added to the `geos_measures` file as it most closely resembles that of `st_length().` Additionally, the example I added uses the objects previously created by the `st_length()` example. 
I am unable to build sf locally so I cannot create the man page myself. Apologies for that! 
Closes https://github.com/r-spatial/sf/issues/268#issuecomment-1837247751, emotionally.
> add st_perimeter()

- R/sample.R
This PR adds `st_sample.bbox()` to provide an S3 method to st_sample() for bbox class object. 
Very often I find myself wanting sample random points over the extent of an sfc object. This requires me to write code such as 
```r
st_bbox(nc) |> 
st_as_sfc() |> 
st_sample(42)
```
It would be quite nice to simplify this to `st_sample(st_bbox(nc), 42)`. This PR makes it possible. 
Again, sorry for not updating `man/st_sample.Rd`. I used to be able to compile sf. I'll figure it out again at some point.
> Add bbox method to st_sample()

- R/geom-transformers.R
- man/geos_unary.Rd
I noticed that the geos_unary docs refer to `sf_use_s2()` as `st_use_s2()`: this PR fixes that incorrect reference.
> Update geos_unary docs to correct wrong function name (st_use_s2() -> sf_use_s2())

- NEWS.md
- R/RcppExports.R
- R/gdal_utils.R
- man/gdal_utils.Rd
- src/RcppExports.cpp
- src/gdal_utils.cpp
- tests/testthat/test_gdal.R
Hi,
as discussed in #2304 this PR adds support for the gdal_footprint utility requiring GDAL >= 3.8.0.
I am very new to C++, so please double-check if everything is ok. I used the script below to check the functionality:
``` r
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.8.1, PROJ 9.1.1; sf_use_s2() is TRUE
tif <- system.file("tif/geomatrix.tif", package = "sf")
t1 <- tempfile(fileext = ".gpkg")
t2 <- tempfile(fileext = ".json")
t3 <- tempfile(fileext = ".gpkg")
t4 <- tempfile(fileext = ".gpkg")
t5 <- tempfile(fileext = ".gpkg")
t6 <- tempfile(fileext = ".gpkg")
gdal_utils("gdalfootprint", tif, t1)
(s1 <- st_read(t1))
#> Reading layer `footprint' from data source `/tmp/RtmpS1pM0Y/file27bf77437ef6.gpkg' using driver `GPKG'
#> Simple feature collection with 1 feature and 0 fields
#> …
```
> Add gdal_footprint support to gdal_utils

- R/graticule.R
As reported in the docs, `reset = FALSE` is used to allow the inclusion of further map elements. Before this change: 
``` r
library(sf)
#> Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
library(maps)
usa = st_as_sf(map('usa', plot = FALSE, fill = TRUE))
laea = st_crs("+proj=laea +lat_0=30 +lon_0=-95") # Lambert equal area
usa <- st_transform(usa, laea)
bb = st_bbox(usa)
bbox = st_linestring(rbind(c( bb[1],bb[2]),c( bb[3],bb[2]),
c( bb[3],bb[4]),c( bb[1],bb[4]),c( bb[1],bb[2])))
g = st_graticule(usa)
plot(usa, xlim = 1.2 * c(-2450853.4, 2186391.9))
plot(g[1], add = TRUE, col = 'grey')
plot(bbox, add = TRUE)
points(g$x_start, g$y_start, col = 'red')
points(g$x_end, g$y_end, col = 'blue')
invisible(lapply(seq_len(nrow(g)), function(i) {
if (g$type[i] == "N" && …
```
> Add reset = FALSE into the plot call

- R/stars.R
- tests/testthat/test_gdal.R
Fix bug that prevented using `config_options` argument to `gdal_addo()`
Reproducible  example:
``` 
library(sf)
dir = file.path(tempdir(), "gdal_addo")
dir.create(dir)
tif = file.path(dir, "geomatrix.tif")
file.copy(system.file("tif/geomatrix.tif", package = "sf"), tif, overwrite = TRUE)
gdal_addo(tif, read_only = TRUE, config_options = c(COMPRESS_OVERVIEW="LZW"))
```
Previously threw error:  *Error: config_options should be a character vector with names, as in c(key="value")*
The problem was caused by calling `as.character(config_options)` which stripped the names before passing it on to `CPL_gdaladdo()`
> fix gdal_addo()

- R/join.R
```r
z <- st_sf(pid=5, geom=st_sfc(st_polygon(list(matrix(c(0,0,4,0,4,4,0,4,0,0),ncol=2, byrow=T)))))
x <- st_sf(id=1:2, geom=st_sfc(st_point(1:2), st_point(2:3)), geom2=st_sfc(st_point(1:2), st_point(2:3)))
st_join(x,z)
Simple feature collection with 2 features and 2 fields
Active geometry column: geom
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 1 ymin: 2 xmax: 2 ymax: 3
CRS:           NA
id pid        geom       geom2
1  1   5 POINT (1 2) POINT (1 2)
2  2   5 POINT (2 3) POINT (2 3)
st_join(x[,'geom'], z)
Simple feature collection with 2 features and 1 field
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 1 ymin: 2 xmax: 2 ymax: 3
CRS:           NA
pid    geometry
1   5 POINT (1 2)
2   5 POINT (2 3)
```
> st_join renames geom column to geometry if x is st_sf with only a st_sfc col

- R/sfc.R
- tests/testthat/test_sfc.R
Fixes the points highlighted here: https://github.com/r-spatial/sf/pull/2059#issuecomment-1906279039 as well as ensuring that the `bbox` gets updated
> Fix value replacement for sfc_POINT

- R/tidyverse-vctrs.R
- tests/testthat/test_vctrs.R
I noticed `dplyr::bind_rows` failed due to `vctrs` returning empty subsets for point matrixes. The quick solution I could find was realize in `vec_proxy`, more elegant would be to keep the point matrix but I'm not sure how to do that as `vctrs` indexes the list. 
Note for the test the bbox needs to be recomputed as `x[0]` produces a bbox without CRS while `vec_slice` has one.
> ensure vctrs operations work

- README.md
Minor edit
podofo-0.9 is not available from pacman, the command returns `target not found podofo-0.9`
Fix: remove "-0.9"
Related: https://github.com/r-spatial/sf/issues/2205
> Fix Arch install example

- DESCRIPTION
- NEWS.md
- R/transform.R
- src/gdal.cpp
Quick fix for `ret` not being allocated in-scope in `CPL_transform_bounds`, added note to NEWS, bumped version number and added test in R code so that compiled code shouldn't be reached with GDAL < 3.4.0 - #2436
> address #2436

- NEWS.md
- R/geom-transformers.R
- tests/gdal_geom.R
Hi :wave:
I set up this PR to address #2442. I am unsure where to best handle this, here or in `s2`? However, I think I am currently not able to contribute to `s2`, so here goes this PR.
Using mapply to iterate over multiple dTolerance values. Also works for a vector of length 1. Needed to wrap `s2::s2_simplify()` with `sf::st_as_sfc()` since the latter seems currently to be unable to coerce a list of `s2_geography` objects to `sfc`.
> address #2442

- vignettes/sf7.Rmd
While reading the vignette "Spherical geometry in sf using s2geometry" I spotted a typo, so here's a PR that fixes it.
> Fix typo in vignette 7

- R/geom-transformers.R
- man/geos_unary.Rd
I have improved the description of `st_buffer()` and I think it should be more explanatory now (for #2455). What do you think?
> improve `st_buffer()` description

- src/gdal_geom.cpp
The current implementation would likely crash on things like OGRPolyhedralSurface.
> CPL_length(): fix unchecked cast to OGRGeometryCollection

- NEWS.md
- R/spatstat.R
- tests/spatstat.R
The conversion sf ---> ppp accepts a dataframe of marks with ncol > 1. Fixes #2450.
> as.ppp.sf accepts ncol(X) > 1

- configure
- configure.ac
See https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/sf-00check.html. First is unneeded, as R >=3.3.0 is required in DESCRIPTION. The second is needed, and the edit works, checked both with _R_CHECK_BASHISMS_=true _R_CHECK_BASHISMS_EXTRA_=true and R-devel, and against a doctored gdal-config reporting 3.6.0.
> fix bashisms

- R/sfg.R
- tests/testthat/test-sfg.R
- tests/testthat/test-wkt.R
The current behavior of `print.sfg()` is surprising because it returns a formatted string, which prevents the usage in a pipeline, e.g.,
```r
sf::st_point(1:2) |>
print() |>
sf::st_sfc() |>
print()
```
As the vast majority of `print()` methods do, side-effect functions should return the original object (see <https://design.tidyverse.org/out-invisible.html>). Actually, `print.sf()` and `print.sfc()` already do this:
https://github.com/r-spatial/sf/blob/5567b747c8e5ad5aafc41ff0cfa103188fdb48e1/R/sf.R#L422-L445
https://github.com/r-spatial/sf/blob/5567b747c8e5ad5aafc41ff0cfa103188fdb48e1/R/sfc.R#L202-L267
> print.sfg() returns the input sfg, not its formatted string
