r-spatial/sf

- vignettes/sfr.Rmd
Great that you've got `sf` on CRAN! Thanks for the enormous effort behind it!
> tidy vignette

- tools/winlibs.R
Give the user a helpful error message when the R version on Windows is too old.
> Check version on Windows

- src/gdal_read.cpp
Thinking: plain English is good!
> Replace ; with . in st_read() message

- src/gdal_read.cpp
These two modifications remain from my PR ... `count_features` only works flawlessly because it's the last thing done with `poLayer` in `CPL_get_layers`, but any other actions might cause problems without calling `ResetReading()`.
> tidy src/gdal_read.cpp

- R/geom.R
- R/sfc.R
- src/bbox.cpp
#testing
```r
nc <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
nc_cent <- st_centroid(nc)
st_distance(nc_cent[F],nc_cent) # this fails because of conditional if `class(x[[1]])[2] != "POINT"`
```
> better class checking in st_distance -- enhanced `str`  function

- R/plot.R
- tests/plot.R
It's better to compute colors for each colum to allow overriding colors. Also dots were not passed.
I'm not sure exactly about how to test that feature, please advise if I should do it otherwise (I was confused between using testthat or not).
#118, 5ca05199231e91576bdcd968fb048ca45eed7377
> fix per column color computation

- tests/dplyr.R
to preserve the dplyr style
#120
> use select()

- R/tidy.R
- tests/plot.R
- tests/testthat/test_tidy.R
> test plot without attributes

- src/Makevars.win
Ensure the download script works, even if people have strange things in their Rprofile.
> ignore rprofile in download script

- R/cast_sfc.R
Quick fix for https://github.com/edzer/sfr/issues/154
> keep CRS on GC

- R/db.R
- tests/pg.R
Fix #102 (will wait for real test on Travis)
> Add warning when writing to postgis with proj4, but no SRID

- R/crs.R
- man/st_crs.Rd
> change the order of NA_crs_

- .gitignore
- DESCRIPTION
- R/aggregate.R
- man/aggregate.sf.Rd
- Add a few dir/files to .gitignore
- Transform `suggests`  and `depends` one item per line (makes it easier to see addition and deletion)
- Add microbenchmark to Depends (it's in sf3 vignette)
- fix roxygen tag in aggregate
> Project files

- .gitignore
- sf.Rproj
This makes life a little easier for those of us who use RStudio
> Add RStudio project

- R/db.R
- tests/testthat/test_postgis.R
Search for tables, views and materialized views when checking read or write.
I couldn't find a generic DBI procedure for that, so it's very PostGIS specific and thus makes it less generic and will probably fail for other databases that don't support views, materialized views or that store them differently. I've also asked the DBI package, just in case.
fix #212
> Check for views and materialized views when reading and writing from db

- vignettes/sf3.Rmd
The current code amounts to just doing `points(0)` on both the line segment and the polygon.
> Fix st_segmentize example in sf3.Rmd

- R/db.R
I got a 5-10x speed improvement for medium datasets depending on the connection speed to the database by simply collapsing all calls before sending. Any idea how large this call can be before it saturates, like Windows shell commands that can't exceed something like 65536 characters.
I believe it will also ensure some basic integrity because the call is performed once, while before it was possible to interrupt the call in the for loop and get some geometries still empty.
I was reluctant to add a test on a large dataset because it would slow down testing, but if you think it's a good idea, I'll add one.
> Minimise database calls

- R/geom.R
- man/geos.Rd
so that user can specify points to sample
> add sample argument to st_line_sample

- src/Makevars.win
- tools/winlibs.R
For details see https://github.com/rwinlib/gdal2#readme
> Update Windows to GDAL 2.2.0 stack

- R/aggregate.R
Demonstrates what happens when features in y do not intersect with x
> Add aggregate.sf example

- tests/testthat/test_crs.R
Awesome @edzer! I didn't know about GDAL isSame. I think adding a test might be useful for maintenance.
> add test for CRS comparison (#180)

- R/geom.R
- man/geos_measures.Rd
> Fix st_length for mixed geometries

- R/transform.R
- README.md
- man/st_transform.Rd
1. Sixth vignette is mentioned in the readme
2. Description of the use_gdal parameter is updated
> Two small changes

- src/proj.cpp
extra cookie for PJ_UNITS in 500
> fix st_proj_info("units") for 5.0.0

- src/gdal.cpp
- src/stars.cpp
> fixes for GDAL 2.3.0 const tightening

- R/geom.R
based on https://github.com/edzer/UseR2017/blob/master/tutorial.Rmd
> Tiny improvement of documentation 

- src/geos.cpp
This PR modifies predicate functions (intersects, contains, etc.) to avoid creating a prepared geometry that will never be used.
> Avoid constructing prepared geometries that are not used

- R/db.R
- tests/testthat/test_postgis_RPostgreSQL.R
> Check for all NAs in character columns when checking for geometry columns

- R/RcppExports.R
- R/read.R
- man/st_read.Rd
- src/RcppExports.cpp
- src/gdal_read.cpp
- tests/testthat/test_read.R
> Dis organization execute sql

- R/db.R
- R/read.R
- man/st_read.Rd
Follows 0703361ed12c3b29b17dcdcbb54263859da8495a
> add `as_tibble` argument for databases

- tic.R
adjust for roxygen2 v6.1.1
klutometis/roxygen#822
> Adjust for latest roxygen2 update

- README.md
Also clean up section headings
> Add cheatsheet link and image to README

- DESCRIPTION
Super minor, but nonetheless :-)
> Fixing name in DESCRIPTION

- DESCRIPTION
> Specify min Rcpp version

- src/ops.cpp
Fixes #994 
I inadvertently passed a string to `Rf_getAttrib` which expects a symbol... this should fix it
> pass symbol to Rf_getAttrib

- src/Makevars.win
Small tweak that will make it easier to update to the next toolchain.
> Tweak Makevars.win for possible future toolchain

- src/geos.cpp
This PR updates `CPL_geos_union` to avoid performing an expensive union of identical geometries, optimizing a usage pattern in which we:
a) perform a non-spatial one-to-many join between `sf` object and a data frame
b) group by an ID that originated in the `sf` object
c) call summarize with the default `do_union = TRUE`
Short code example:
```
nc <- st_read(system.file("shape/nc.shp", package='sf'))
data <- data.frame(FIPS=rep(nc$FIPS, each=3),
year=rep(c(1990, 2000, 2010), times=nrow(nc)),
obs=runif(n=3*nrow(nc), min=10, max=20))
a <- nc %>%
inner_join(data) %>%
group_by(FIPS) %>%
summarize(max_obs=max(obs))
```
In this case the `summarize()` call takes, on average:
| |  `do_union=TRUE` |  `do_union=FALSE` |
| -- | -- | --- |
this branch | 80 ms | 78 ms |
master branch | 148 ms | 76 ms | …
> Avoid union of identical geometries in summarize()

- R/geom.R
- man/geos_unary.Rd
This is a minor change but confident it's an improvement, especially for people new to buffers who may get confused by all the options. The page linked to is exemplary: https://postgis.net/docs/ST_Buffer.html
> Add link explaining st_buffer options

- tic.R
see https://github.com/r-spatial/sf/pull/841#issuecomment-496009297
> pkgdown: use tic macro for deployment

- R/db.R
- tests/testthat/test_postgis_RPostgreSQL.R
@edzer here's the code coverage completion (#1061)!
> Complete code coverage for database 

- R/join.R
- man/st_join.Rd
Motivated by https://github.com/r-spatial/sf/issues/990
> Add a couple of predicates to st_join doc, format as list

- src/wkb.cpp
- Make wkb_read function inline
- Use Rcpp::no_init
Reduces overall time of CPL_read_wkb by about 50%, most of which is due
to the inlining. Another roughly 15% is possible by avoiding checking the
buffer length before every single read, and by making specialized
versions of the read_numeric_matrix for the supported cases of 2, 3, and
4 dimensions. These changes are a bit more invasive and are not included
here.
> Optimize reading sf geometries from WKB

- src/wkb.cpp
This should resolve #1152 . I tested it using the `rocker/r-devel-san` container.
> Resolve UBSAN error in wkb_read

- R/tidyverse-vctrs.R
Follow up to https://github.com/r-spatial/sf/commit/83c2d99eec33334d147a7b1a1d879627f57b42d8
> Merge conflict resolution part II

- R/gdal_utils.R
- man/gdal_utils.Rd
Following the discussion in #1213, I added one example at gdal_utils help page. I added the \dontrun tag so that it doesn't create a new object everytime it tests the examples but maybe it would be fine.
> Add one example to gdal_utils

- R/sf.R
- man/sf.Rd
Closes #1251 
Thanks @edzer, I added a quick blurb with more detail, feel free to adjust as you see fit.
Again my editor removed some trailing whitespace it seems; `-w` version:
https://github.com/r-spatial/sf/pull/1252/files?w=1
> add a blurb to ?st_sf about agr argument

- DESCRIPTION
- R/crs.R
- configure
- configure.ac
> SetFromUserInput update version and configure

- src/stars.cpp
Currently, GDAL raster read invalidates the default geotransform setting it to NA, so we cannot plot non-geo rasters read with stars: 
https://github.com/r-spatial/sf/blob/master/src/stars.cpp#L312-L318
Is there any reason not to return the default transform (0,1,0,0,0,1)?  https://gdal.org/doxygen/classGDALDataset.html#a5101119705f5fa2bc1344ab26f66fd1d
Currently: 
```R
f <- file.path(R.home(), "Tcl/lib/tk8.6/images/logo100.gif")
sf::gdal_read(f)$geotransform
#[1] NA NA NA NA NA NA
```
I'm inclined to detect the situation and set it to (0,1,0,0,0, -1) so that stars plots in the likely correct orientation, with a warning as is common in geo-sw that reads images. But, that also means we should consider shifting the raster up to put it in [xmin = 0, ymin = 0, xmax = ncol, ymax = nrow] (a …
> default geotransform

- tests/testthat/test_postgis_RPostgres.R
RPostgres is not available for solaris
close #1321
> Early skip for solaris

- DESCRIPTION
- R/tidyverse-vctrs.R
- man/db_drivers.Rd
- man/extension_map.Rd
- man/prefix_map.Rd
- man/st_agr.Rd
- man/st_bbox.Rd
- man/st_crs.Rd
- man/st_m_range.Rd
- man/st_z_range.Rd
- man/tidyverse.Rd
Tweaking tags in one place now gives better method documentation.
> Document with roxygen2 7.1.0

- .Rbuildignore
- .github/workflows/R-CMD-check-with-db.yaml
- .github/workflows/R-CMD-check.yaml
- R/crs.R
- man/st_crs.Rd
This replaces #1323 with the same changes but a cleaner history. @edzer @etiennebr. Partly addresses #1309.
> Actions macos

- tests/testthat/test_sp.R
- tests/testthat/test_zm_range.R
> Avoid showing messages during loading

- R/crs.R
Foreshadowing upcoming changes in the crs slot of Raster objects
> For upcoming changes in "raster"

- tools/winlibs.R
The structure of the winlibs path is different in version 3
> winlibs path fix

- R/tidyverse.R
- tests/testthat/test_tidy.R
This method is used to restore the class of the output of `bind_rows()` and `bind_cols()` to the class of the first input.
With CRAN dplyr:
```r
sf1 = st_sf(x = 1, y = st_sfc(st_point(0:1)))
sf2 = st_sf(z = st_sfc(st_point(2:3)), x = 2)
bind_rows(sf1, sf2)
#> Error in .subset2(x, i, exact = exact) :
#>   attempt to select less than one element in get1index
#> In addition: Warning messages:
#> 1: In bind_rows_(x, .id) :
#>   Vectorizing 'sfc_POINT' elements may not preserve their attributes
#> 2: In bind_rows_(x, .id) :
#>   Vectorizing 'sfc_POINT' elements may not preserve their attributes
```
With dplyr 1.0:
```r
bind_rows(sf1, sf2)
#> Simple feature collection with 2 features and 1 field
#> Active geometry column: y (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY …
```
> Add `dplyr_reconstruct()` method

- DESCRIPTION
- NEWS.md
- R/tidyverse.R
- tests/testthat/test_tidy.R
> Fix renaming of geometry columns in `dplyr::select()`

- R/tidyverse-vctrs.R
- tests/testthat/test_vctrs.R
Reverts #1335
Part of r-lib/vctrs#1136
cc @krlmlr
> Fix restoration of sfc lists

- NEWS.md
- R/tidyverse.R
- tests/testthat/test_tidy.R
> Preserve geometry column in `rename()`

- NEWS.md
- R/tidyverse.R
- tests/testthat/test_tidy.R
> Ensure back-stickiness in `select()`

- README.md
Realise after looking at http://r-spatial.github.io/sf/ that this will be easier to read and use, and is consistent with other code chunks in the readme.
> Move shell command onto 1 line

- R/geom-transformers.R
correct a small mistake in the document of "geom-transformers.R"
> correct a small mistake in the document

- R/tidyverse.R
> Ensure `dplyr_reconstruct.sf` returns tibbles

- R/tidyverse.R
This is passed through to st_union and allows for better performance in
cases where the inputs are known to have no overlaps.
> Add is_coverage argument to summarize method

- NEWS.md
> Add NEWS entry

- R/sp.R
This works for the simple test case in the issue.
> handle coercion to sf of degenerate sp single coord. lines #1559

- tests/testthat/test_geos.R
Light-touch conversion in-test for version checking, in this branch because that was where I was.
> fixes #1653 on branch

- .github/workflows/tic-db.yml
- .github/workflows/tic.yml
{tic} templates can be updated :rocket: :robot:
> Update tic templates [ci-skip]

- src/stars.cpp
This appears to fix r[spatial/stars#459](https://github.com/r-spatial/stars/issues/459) by initializing variables for `poDataset->GetRasterXSize()` and `poDataset->GetRasterYSize()`, before they are accessed in an `if()` statement.
> CPL_extract: initialize xsize and ysize

- src/geos.cpp
This should help Ctrl-C do a better job interrupting.
> Pass interrupt requests from R to GEOS

- R/join.R
Closes https://github.com/r-spatial/sf/issues/2070
> add st_filter example

- .Rbuildignore
- .gitattributes
- .github/workflows/tic.yml
`autoconf.ac` is precious, needs to be checked out with LF style.
> Reenable CI/CD on Windows

- src/proj.cpp
omission in 8c29e95a4718261dccf307408677d8f788ec293c
> Fix coverage action

- R/transform.R
- man/st_transform.Rd
- tests/crs.R
- tests/empty.R
> update EPSG code in docs (fix #2402)

- src/gdal_geom.cpp
Fixes #2466
Half-imposter here: I don't even know how to build locally. I managed to get past the ./configure stage, but lacks the familiar "make" of C/C++ addicts ;-)
> CPL_area(): use proper casts to OGRGeometry subtypes, in particular to fix issues with GeometryCollection of Polygon
